version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db_postgres_eventos
    environment:
      POSTGRES_DB: eventos_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventos-net

volumes:
  postgres_data:

networks:
  eventos-net:
