name: Gestao de Eventos Application
#Define em que momento queremos que ele execute
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
          cache-dependency-path: "sub-project/pom.xml" # optional
      - name: Build with Maven
        run: mvn -B package --file pom.xml
